# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Beispiel: § 3 SächsPolG: Polizeiliche Generalklausel', max_length=255, verbose_name='Titel')),
                ('button_text', models.CharField(help_text='Maximal 20 Zeichen. Beispiel: § 3 PolG', max_length=20, verbose_name='Text für den Button')),
                ('content', models.TextField(blank=True, help_text='Beispiel: &lt;p&gt;Erster Absatz&lt;/p&gt;&lt;p&gt;Zweiter Absatz&lt;/p&gt;', verbose_name='Inhalt (HTML)')),
                ('weight', models.IntegerField(default=0, help_text='Je größer die Zahl, desto weiter hinten/unten ist der Button einsortiert.', verbose_name='Gewichtung')),
            ],
            options={
                'ordering': ('weight',),
                'verbose_name_plural': 'Zusatzfolien',
                'verbose_name': 'Zusatzfolie',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(help_text='Die Gliederungszeichen aller Ebenen werden zusammengesetzt. Beispiel: Aus b) wird § 3 II. 2. b).', max_length=10, verbose_name='Gliederungszeichen')),
                ('title', models.CharField(help_text='Beispiel: Inanspruchnahme Nichtverantwortlicher', max_length=255, verbose_name='Gliederungsüberschrift')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vorlesung_enders_server.Topic')),
            ],
            options={
                'verbose_name_plural': 'Gliederungspunkte',
                'verbose_name': 'Gliederungspunkt',
            },
        ),
    ]
