# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorlesung_enders_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ('category', 'weight'), 'verbose_name': 'Zusatzfolie', 'verbose_name_plural': 'Zusatzfolien'},
        ),
        migrations.AddField(
            model_name='slide',
            name='category',
            field=models.CharField(default='Vorschriften', help_text='Beispiel: Fälle', max_length=255, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_text',
            field=models.CharField(help_text='Maximal 20 Zeichen. Beispiel: § 3 PolG', max_length=255, verbose_name='Text für den Button'),
        ),
    ]
