# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorlesung_enders_server', '0002_auto_20170324_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='button_text',
            field=models.CharField(help_text='Bitte nur wenige Zeichen verwenden. Beispiel: § 3 PolG', max_length=255, verbose_name='Text für den Button'),
        ),
    ]
